//
// Generated file, do not edit! Created by nedtool 4.6 from inetveins/common/TLVOption.msg.
//

#ifndef _INETVEINS_TLVOPTION_M_H_
#define _INETVEINS_TLVOPTION_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// cplusplus {{
#include "INETDefs.h"
// }}


namespace inetveins {

/**
 * Class generated from <tt>inetveins/common/TLVOption.msg:28</tt> by nedtool.
 * <pre>
 * class TLVOptionBase
 * {
 *     short type = -1;
 *     short length = 0;   // total length of option
 * }
 * </pre>
 */
class TLVOptionBase : public ::cObject
{
  protected:
    short type_var;
    short length_var;

  private:
    void copy(const TLVOptionBase& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const TLVOptionBase&);

  public:
    TLVOptionBase();
    TLVOptionBase(const TLVOptionBase& other);
    virtual ~TLVOptionBase();
    TLVOptionBase& operator=(const TLVOptionBase& other);
    virtual TLVOptionBase *dup() const {return new TLVOptionBase(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual short getType() const;
    virtual void setType(short type);
    virtual short getLength() const;
    virtual void setLength(short length);
};

inline void doPacking(cCommBuffer *b, TLVOptionBase& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, TLVOptionBase& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>inetveins/common/TLVOption.msg:34</tt> by nedtool.
 * <pre>
 * class TLVOptionRaw extends TLVOptionBase
 * {
 *     char bytes[];
 * }
 * </pre>
 */
class TLVOptionRaw : public ::inetveins::TLVOptionBase
{
  protected:
    char *bytes_var; // array ptr
    unsigned int bytes_arraysize;

  private:
    void copy(const TLVOptionRaw& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const TLVOptionRaw&);

  public:
    TLVOptionRaw();
    TLVOptionRaw(const TLVOptionRaw& other);
    virtual ~TLVOptionRaw();
    TLVOptionRaw& operator=(const TLVOptionRaw& other);
    virtual TLVOptionRaw *dup() const {return new TLVOptionRaw(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual void setBytesArraySize(unsigned int size);
    virtual unsigned int getBytesArraySize() const;
    virtual char getBytes(unsigned int k) const;
    virtual void setBytes(unsigned int k, char bytes);
};

inline void doPacking(cCommBuffer *b, TLVOptionRaw& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, TLVOptionRaw& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>inetveins/common/TLVOption.msg:39</tt> by nedtool.
 * <pre>
 * class TLVOptions
 * {
 *     @customize(true);
 *     abstract TLVOptionBase tlvOption[];
 * }
 * </pre>
 *
 * TLVOptions_Base is only useful if it gets subclassed, and TLVOptions is derived from it.
 * The minimum code to be written for TLVOptions is the following:
 *
 * <pre>
 * class TLVOptions : public TLVOptions_Base
 * {
 *   private:
 *     void copy(const TLVOptions& other) { ... }

 *   public:
 *     TLVOptions() : TLVOptions_Base() {}
 *     TLVOptions(const TLVOptions& other) : TLVOptions_Base(other) {copy(other);}
 *     TLVOptions& operator=(const TLVOptions& other) {if (this==&other) return *this; TLVOptions_Base::operator=(other); copy(other); return *this;}
 *     virtual TLVOptions *dup() const {return new TLVOptions(*this);}
 *     // ADD CODE HERE to redefine and implement pure virtual functions from TLVOptions_Base
 * };
 * </pre>
 *
 * The following should go into a .cc (.cpp) file:
 *
 * <pre>
 * Register_Class(TLVOptions);
 * </pre>
 */
class TLVOptions_Base : public ::cObject
{
  protected:

  private:
    void copy(const TLVOptions_Base& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const TLVOptions_Base&);
    // make constructors protected to avoid instantiation
    TLVOptions_Base();
    TLVOptions_Base(const TLVOptions_Base& other);
    // make assignment operator protected to force the user override it
    TLVOptions_Base& operator=(const TLVOptions_Base& other);

  public:
    virtual ~TLVOptions_Base();
    virtual TLVOptions_Base *dup() const {throw cRuntimeError("You forgot to manually add a dup() function to class TLVOptions");}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual void setTlvOptionArraySize(unsigned int size) = 0;
    virtual unsigned int getTlvOptionArraySize() const = 0;
    virtual TLVOptionBase& getTlvOption(unsigned int k) = 0;
    virtual const TLVOptionBase& getTlvOption(unsigned int k) const {return const_cast<TLVOptions_Base*>(this)->getTlvOption(k);}
    virtual void setTlvOption(unsigned int k, const TLVOptionBase& tlvOption) = 0;
};

} // namespace inetveins

#endif // ifndef _INETVEINS_TLVOPTION_M_H_

