//
// Generated file, do not edit! Created by nedtool 4.6 from networklayer/bgpv4/BGPMessage/BGPASPathSegment.msg.
//

#ifndef _BGPASPATHSEGMENT_M_H_
#define _BGPASPATHSEGMENT_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Enum generated from <tt>networklayer/bgpv4/BGPMessage/BGPASPathSegment.msg:19</tt> by nedtool.
 * <pre>
 * enum BGPPathSegmentType
 * {
 * 
 *     AS_SET = 1;
 *     AS_SEQUENCE = 2;
 * }
 * </pre>
 */
enum BGPPathSegmentType {
    AS_SET = 1,
    AS_SEQUENCE = 2
};

/**
 * Class generated from <tt>networklayer/bgpv4/BGPMessage/BGPASPathSegment.msg:28</tt> by nedtool.
 * <pre>
 * //
 * // Represents a BGPv4 AS_PATH path attribute (RFC 4271 Section 4.3)
 * //
 * class BGPASPathSegment
 * {
 *     unsigned char type @enum(BGPPathSegmentType);
 *     unsigned char length;
 *     unsigned short asValue[];
 * }
 * </pre>
 */
class BGPASPathSegment : public ::cObject
{
  protected:
    unsigned char type_var;
    unsigned char length_var;
    unsigned short *asValue_var; // array ptr
    unsigned int asValue_arraysize;

  private:
    void copy(const BGPASPathSegment& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const BGPASPathSegment&);

  public:
    BGPASPathSegment();
    BGPASPathSegment(const BGPASPathSegment& other);
    virtual ~BGPASPathSegment();
    BGPASPathSegment& operator=(const BGPASPathSegment& other);
    virtual BGPASPathSegment *dup() const {return new BGPASPathSegment(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual unsigned char getType() const;
    virtual void setType(unsigned char type);
    virtual unsigned char getLength() const;
    virtual void setLength(unsigned char length);
    virtual void setAsValueArraySize(unsigned int size);
    virtual unsigned int getAsValueArraySize() const;
    virtual unsigned short getAsValue(unsigned int k) const;
    virtual void setAsValue(unsigned int k, unsigned short asValue);
};

inline void doPacking(cCommBuffer *b, BGPASPathSegment& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, BGPASPathSegment& obj) {obj.parsimUnpack(b);}


#endif // ifndef _BGPASPATHSEGMENT_M_H_

