//
// Generated file, do not edit! Created by nedtool 4.6 from linklayer/xmac/XMacPkt.msg.
//

#ifndef _INET_XMACPKT_M_H_
#define _INET_XMACPKT_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// cplusplus {{
#include "inet/linklayer/base/MACFrameBase_m.h"
// }}


namespace inet {

/**
 * Class generated from <tt>linklayer/xmac/XMacPkt.msg:15</tt> by nedtool.
 * <pre>
 * packet XMacPkt extends MACFrameBase
 * {
 *     int preambleCont;
 *     MACAddress destinationAddress[]; // currently known occupied slots
 * }
 * </pre>
 */
class XMacPkt : public ::inet::MACFrameBase
{
  protected:
    int preambleCont_var;
    MACAddress *destinationAddress_var; // array ptr
    unsigned int destinationAddress_arraysize;

  private:
    void copy(const XMacPkt& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const XMacPkt&);

  public:
    XMacPkt(const char *name=NULL, int kind=0);
    XMacPkt(const XMacPkt& other);
    virtual ~XMacPkt();
    XMacPkt& operator=(const XMacPkt& other);
    virtual XMacPkt *dup() const {return new XMacPkt(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getPreambleCont() const;
    virtual void setPreambleCont(int preambleCont);
    virtual void setDestinationAddressArraySize(unsigned int size);
    virtual unsigned int getDestinationAddressArraySize() const;
    virtual MACAddress& getDestinationAddress(unsigned int k);
    virtual const MACAddress& getDestinationAddress(unsigned int k) const {return const_cast<XMacPkt*>(this)->getDestinationAddress(k);}
    virtual void setDestinationAddress(unsigned int k, const MACAddress& destinationAddress);
};

inline void doPacking(cCommBuffer *b, XMacPkt& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, XMacPkt& obj) {obj.parsimUnpack(b);}

} // namespace inet

#endif // ifndef _INET_XMACPKT_M_H_

