//
// Generated file, do not edit! Created by nedtool 4.6 from inet/linklayer/base/MACFrameBase.msg.
//

#ifndef _INET_MACFRAMEBASE_M_H_
#define _INET_MACFRAMEBASE_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// cplusplus {{
   #include "inet/linklayer/common/MACAddress.h"
// }}


namespace inet {

/**
 * Class generated from <tt>inet/linklayer/base/MACFrameBase.msg:27</tt> by nedtool.
 * <pre>
 * packet MACFrameBase
 * {
 *     MACAddress srcAddr;
 *     MACAddress destAddr;
 * }
 * </pre>
 */
class MACFrameBase : public ::cPacket
{
  protected:
    MACAddress srcAddr_var;
    MACAddress destAddr_var;

  private:
    void copy(const MACFrameBase& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const MACFrameBase&);

  public:
    MACFrameBase(const char *name=NULL, int kind=0);
    MACFrameBase(const MACFrameBase& other);
    virtual ~MACFrameBase();
    MACFrameBase& operator=(const MACFrameBase& other);
    virtual MACFrameBase *dup() const {return new MACFrameBase(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual MACAddress& getSrcAddr();
    virtual const MACAddress& getSrcAddr() const {return const_cast<MACFrameBase*>(this)->getSrcAddr();}
    virtual void setSrcAddr(const MACAddress& srcAddr);
    virtual MACAddress& getDestAddr();
    virtual const MACAddress& getDestAddr() const {return const_cast<MACFrameBase*>(this)->getDestAddr();}
    virtual void setDestAddr(const MACAddress& destAddr);
};

inline void doPacking(cCommBuffer *b, MACFrameBase& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, MACFrameBase& obj) {obj.parsimUnpack(b);}

} // namespace inet

#endif // ifndef _INET_MACFRAMEBASE_M_H_

