//
// Generated file, do not edit! Created by nedtool 4.6 from networklayer/rsvp_te/RSVPHello.msg.
//

#ifndef _INET_RSVPHELLO_M_H_
#define _INET_RSVPHELLO_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// cplusplus {{
#include "inet/networklayer/rsvp_te/RSVPPacket.h"
// }}


namespace inet {

/**
 * Class generated from <tt>networklayer/rsvp_te/RSVPHello.msg:30</tt> by nedtool.
 * <pre>
 * //
 * // FIXME missing documentation
 * //
 * packet RSVPHelloMsg extends RSVPMessage
 * {
 *     @customize(true);
 *     bool request;
 *     bool ack;
 * 
 *     int srcInstance;
 *     int dstInstance;
 * 
 *     int rsvpKind = HELLO_MESSAGE;
 * }
 * </pre>
 *
 * RSVPHelloMsg_Base is only useful if it gets subclassed, and RSVPHelloMsg is derived from it.
 * The minimum code to be written for RSVPHelloMsg is the following:
 *
 * <pre>
 * class RSVPHelloMsg : public RSVPHelloMsg_Base
 * {
 *   private:
 *     void copy(const RSVPHelloMsg& other) { ... }

 *   public:
 *     RSVPHelloMsg(const char *name=NULL, int kind=0) : RSVPHelloMsg_Base(name,kind) {}
 *     RSVPHelloMsg(const RSVPHelloMsg& other) : RSVPHelloMsg_Base(other) {copy(other);}
 *     RSVPHelloMsg& operator=(const RSVPHelloMsg& other) {if (this==&other) return *this; RSVPHelloMsg_Base::operator=(other); copy(other); return *this;}
 *     virtual RSVPHelloMsg *dup() const {return new RSVPHelloMsg(*this);}
 *     // ADD CODE HERE to redefine and implement pure virtual functions from RSVPHelloMsg_Base
 * };
 * </pre>
 *
 * The following should go into a .cc (.cpp) file:
 *
 * <pre>
 * Register_Class(RSVPHelloMsg);
 * </pre>
 */
class RSVPHelloMsg_Base : public ::inet::RSVPMessage
{
  protected:
    bool request_var;
    bool ack_var;
    int srcInstance_var;
    int dstInstance_var;
    int rsvpKind_var;

  private:
    void copy(const RSVPHelloMsg_Base& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const RSVPHelloMsg_Base&);
    // make constructors protected to avoid instantiation
    RSVPHelloMsg_Base(const char *name=NULL, int kind=0);
    RSVPHelloMsg_Base(const RSVPHelloMsg_Base& other);
    // make assignment operator protected to force the user override it
    RSVPHelloMsg_Base& operator=(const RSVPHelloMsg_Base& other);

  public:
    virtual ~RSVPHelloMsg_Base();
    virtual RSVPHelloMsg_Base *dup() const {throw cRuntimeError("You forgot to manually add a dup() function to class RSVPHelloMsg");}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual bool getRequest() const;
    virtual void setRequest(bool request);
    virtual bool getAck() const;
    virtual void setAck(bool ack);
    virtual int getSrcInstance() const;
    virtual void setSrcInstance(int srcInstance);
    virtual int getDstInstance() const;
    virtual void setDstInstance(int dstInstance);
    virtual int getRsvpKind() const;
    virtual void setRsvpKind(int rsvpKind);
};

} // namespace inet

#endif // ifndef _INET_RSVPHELLO_M_H_

