//
// Generated file, do not edit! Created by nedtool 4.6 from inet/transport/rtp/reports.msg.
//

#ifndef _REPORTS_M_H_
#define _REPORTS_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>inet/transport/rtp/reports.msg:15</tt> by nedtool.
 * <pre>
 * //
 * // Represents an RTP sender report as contained
 * // in an ~RTCPSenderReportPacket.
 * //
 * class SenderReport
 * {
 *     @customize(true);
 * 
 *     // The ntp time stamp.
 *     uint64 NTPTimeStamp;
 * 
 *     // The rtp time stamp.
 *     uint32 RTPTimeStamp;
 * 
 *     // The number of packets sent.
 *     uint32 packetCount;
 * 
 *     // The number of (payload) bytes sent.
 *     uint32 byteCount;
 * }
 * </pre>
 *
 * SenderReport_Base is only useful if it gets subclassed, and SenderReport is derived from it.
 * The minimum code to be written for SenderReport is the following:
 *
 * <pre>
 * class SenderReport : public SenderReport_Base
 * {
 *   private:
 *     void copy(const SenderReport& other) { ... }

 *   public:
 *     SenderReport() : SenderReport_Base() {}
 *     SenderReport(const SenderReport& other) : SenderReport_Base(other) {copy(other);}
 *     SenderReport& operator=(const SenderReport& other) {if (this==&other) return *this; SenderReport_Base::operator=(other); copy(other); return *this;}
 *     virtual SenderReport *dup() const {return new SenderReport(*this);}
 *     // ADD CODE HERE to redefine and implement pure virtual functions from SenderReport_Base
 * };
 * </pre>
 *
 * The following should go into a .cc (.cpp) file:
 *
 * <pre>
 * Register_Class(SenderReport);
 * </pre>
 */
class SenderReport_Base : public ::cObject
{
  protected:
    uint64 NTPTimeStamp_var;
    uint32 RTPTimeStamp_var;
    uint32 packetCount_var;
    uint32 byteCount_var;

  private:
    void copy(const SenderReport_Base& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const SenderReport_Base&);
    // make constructors protected to avoid instantiation
    SenderReport_Base();
    SenderReport_Base(const SenderReport_Base& other);
    // make assignment operator protected to force the user override it
    SenderReport_Base& operator=(const SenderReport_Base& other);

  public:
    virtual ~SenderReport_Base();
    virtual SenderReport_Base *dup() const {throw cRuntimeError("You forgot to manually add a dup() function to class SenderReport");}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual uint64 getNTPTimeStamp() const;
    virtual void setNTPTimeStamp(uint64 NTPTimeStamp);
    virtual uint32 getRTPTimeStamp() const;
    virtual void setRTPTimeStamp(uint32 RTPTimeStamp);
    virtual uint32 getPacketCount() const;
    virtual void setPacketCount(uint32 packetCount);
    virtual uint32 getByteCount() const;
    virtual void setByteCount(uint32 byteCount);
};

/**
 * Class generated from <tt>inet/transport/rtp/reports.msg:36</tt> by nedtool.
 * <pre>
 * //
 * // Rrepresents an RTP receiver report stored
 * // in an RTPSenderReportPacket or RTPReceiverReport.
 * //
 * class ReceptionReport
 * {
 *     @customize(true);
 * 
 *     // The ssrc identifier of the sender this ~ReceptionReport is for.
 *     uint32 ssrc;
 * 
 *     // The fraction lost.
 *     uint8 fractionLost;
 * 
 *     // The number of packets expected minus the number of packets received.
 *     int packetsLostCumulative;
 * 
 *     // The extended highest sequence number received.
 *     uint32 sequenceNumber;
 * 
 *     // The interarrival jitter.
 *     int jitter;
 * 
 *     // The rtp time stamp of the last ~SenderReport received from this source.
 *     int lastSR;
 * 
 *     // The delay since the last ~SenderReport from this sender has been
 *     // received in units of 1/65536 seconds.
 *     int delaySinceLastSR;
 * }
 * </pre>
 *
 * ReceptionReport_Base is only useful if it gets subclassed, and ReceptionReport is derived from it.
 * The minimum code to be written for ReceptionReport is the following:
 *
 * <pre>
 * class ReceptionReport : public ReceptionReport_Base
 * {
 *   private:
 *     void copy(const ReceptionReport& other) { ... }

 *   public:
 *     ReceptionReport() : ReceptionReport_Base() {}
 *     ReceptionReport(const ReceptionReport& other) : ReceptionReport_Base(other) {copy(other);}
 *     ReceptionReport& operator=(const ReceptionReport& other) {if (this==&other) return *this; ReceptionReport_Base::operator=(other); copy(other); return *this;}
 *     virtual ReceptionReport *dup() const {return new ReceptionReport(*this);}
 *     // ADD CODE HERE to redefine and implement pure virtual functions from ReceptionReport_Base
 * };
 * </pre>
 *
 * The following should go into a .cc (.cpp) file:
 *
 * <pre>
 * Register_Class(ReceptionReport);
 * </pre>
 */
class ReceptionReport_Base : public ::cObject
{
  protected:
    uint32 ssrc_var;
    uint8 fractionLost_var;
    int packetsLostCumulative_var;
    uint32 sequenceNumber_var;
    int jitter_var;
    int lastSR_var;
    int delaySinceLastSR_var;

  private:
    void copy(const ReceptionReport_Base& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const ReceptionReport_Base&);
    // make constructors protected to avoid instantiation
    ReceptionReport_Base();
    ReceptionReport_Base(const ReceptionReport_Base& other);
    // make assignment operator protected to force the user override it
    ReceptionReport_Base& operator=(const ReceptionReport_Base& other);

  public:
    virtual ~ReceptionReport_Base();
    virtual ReceptionReport_Base *dup() const {throw cRuntimeError("You forgot to manually add a dup() function to class ReceptionReport");}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual uint32 getSsrc() const;
    virtual void setSsrc(uint32 ssrc);
    virtual uint8 getFractionLost() const;
    virtual void setFractionLost(uint8 fractionLost);
    virtual int getPacketsLostCumulative() const;
    virtual void setPacketsLostCumulative(int packetsLostCumulative);
    virtual uint32 getSequenceNumber() const;
    virtual void setSequenceNumber(uint32 sequenceNumber);
    virtual int getJitter() const;
    virtual void setJitter(int jitter);
    virtual int getLastSR() const;
    virtual void setLastSR(int lastSR);
    virtual int getDelaySinceLastSR() const;
    virtual void setDelaySinceLastSR(int delaySinceLastSR);
};


#endif // ifndef _REPORTS_M_H_

