//
// Generated file, do not edit! Created by opp_msgc 4.4 from src/routing/aodv-uu/VS_aodv_msg_struct.msg.
//

#ifndef _VS_AODV_MSG_STRUCT_M_H_
#define _VS_AODV_MSG_STRUCT_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0404
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// cplusplus {{
#include "VS_AODV_msg_struct.h"
// }}




#endif // _VS_AODV_MSG_STRUCT_M_H_
